# This file was generated by GoReleaser. DO NOT EDIT.
class Terracost < Formula
  desc "AWS cost estimation for Terraform projects."
  homepage "https://github.com/kainosnoema/terracost-cli"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kainosnoema/terracost-cli/releases/download/v0.1.0/terracost-cli_MacOS_x86_64.tar.gz"
    sha256 "885d3d38593cdc3ce0496dbf47790b001c6a40a380efb6f4cf85e5a610b5403b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kainosnoema/terracost-cli/releases/download/v0.1.0/terracost-cli_Linux_x86_64.tar.gz"
      sha256 "710c91ed69b95594a9dc63ea95a8dd05e80385acdfee2aeb5e09d2f93cbdaf61"
    end
  end

  def install
    bin.install "terracost"
  end
end
